language: java
java:
  - 1.8
jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

addons:
  sonarqube: true
  srcclr: true
env:
  global:
    - secure: SONAR_TOKEN=c85312f9026df6e3a31e017fa5c14b0c43258993

before_script:
 - export JAVA_HOME=/usr/lib/jvm/java-8-oracle


script:
  - cd CRUD-Entidades
  - mvn clean install
  - cd ..
  - cd OptaPlanner-Solution
  - mvn clean install
  - cd ..
  - cd SistemaAlocacao
  - mvn clean install
  - mvn clean install sonar:sonar -Dsonar.login=c85312f9026df6e3a31e017fa5c14b0c43258993

notifications:
  slack: bsi-ifes:nECNqvrLZq1fjJz6C88BjfXk
